/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.kraby.mendingtradenerf;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    // @Test void someLibraryMethodReturnsTrue() {
    //     MendingTradeNerf classUnderTest = new MendingTradeNerf();
    //     // assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    //     assertTrue(classUnderTest != null);
    // }
}
